import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Locale, i18n } from "@/i18n/config";
import "locomotive-scroll/dist/locomotive-scroll.css";
import "../../styles/globals.css";
import "../../styles/tailwind.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Isabella Lizarralde Arias",
  description: "Generated by create next app",
};

export async function getStaticParams() {
  return i18n.locales.map((lang) => ({ params: { lang } }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
